version: '3'
services:
  node:
    build: .
    network_mode: 'host'
    privileged: true
    restart: always
  influxdb:
    image: 'influxdb:1.7.0'
    restart: always
    ports:
      - '8086:8086'
    volumes:
      - 'influxdb:/var/lib/influxdb'
  chronograf:
    image: 'chronograf:1.7.2'
    restart: always
    volumes:
      - 'chronograf:/var/lib/chronograf'
    ports:
      - '8888:8888'
    links:
      - influxdb

volumes:
  influxdb:
  chronograf:
